### ISSUE TITLE
issue running the file  imgCrop = img[y:y+h, x:x+w]

### ISSUE THREAD

**Issue by wcqrwtqr** [EvilPort2/Sign-Language#1]
Hi,
I've been trying to run the python files on my mac but every time I face the same error.

 File "create_gestures.py", line 64, in store_images
    imgCrop = img[y:y+h, x:x+w]

File "fun_util.py", line 53, in recognize
    imgCrop = img[y:y+h, x:x+w]
TypeError: 'NoneType' object is not subscriptable

File "recognize_gesture.py", line 96, in recognize
    imgCrop = img[y:y+h, x:x+w]
TypeError: 'NoneType' object is not subscriptable

What do you think might be the issue

**Comment by wcqrwtqr** [comment]
![screen shot 2018-02-24 at 10 50 52 pm](https://user-images.githubusercontent.com/25097182/36634480-2e440678-19b6-11e8-8b37-eaaa2ec4d9dc.jpg)

**Comment by pvqthang** [comment]
I believe the issue lie in the function cv2.VideoCapture(1). Have you check your camera driver in Mac was installed properly or did you use the correct device?

**Comment by EvilPort2** [comment]
Read the docs of the VideoCapture method of OpenCV. You will be able to solve the error.

**Comment by pvqthang** [comment]
Try cv2.videocapture(0), the system will use your default camera on your pc and it should work

**Comment by prakharcode** [comment]
@EvilPort2  As a matter of good coding practice you might want to catch exception for hardware dependencies.

**Comment by EvilPort2** [comment]
The bug has been fixed

**Comment by adyegora** [comment]
How did you fix the problem? I'm also having the same issue
