### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by lohithareddym** [EvilPort2/Sign-Language#16]
this is my error:
ImportError: Could not find 'nvcuda.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Typically it is installed in 'C:\Windows\System32'. If it is not present, ensure that you have a CUDA-capable GPU with the correct driver installed.
ca you please say me what is the procedure to getrid of this error.

**Comment by EvilPort2** [comment]
I think GPU drivers are not installed correctly. Check the tensorflow GPU installation tutorial on the Tensorflow website.
