### ISSUE TITLE
Two undefined names: 'process_image' and 'imgCrop'

### ISSUE THREAD

**Issue by cclauss** [EvilPort2/Sign-Language#2]
flake8 testing of https://github.com/EvilPort2/Sign-Language

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./recognize_gesture.py:32:20: F821 undefined name 'process_image'
	processed_array = process_image(image)
                          ^
./set_hand_hist.py:32:27: F821 undefined name 'imgCrop'
			hsvCrop = cv2.cvtColor(imgCrop, cv2.COLOR_BGR2HSV)
                                               ^
2     F821 undefined name 'process_image'
```

Is the imgCrop issue related to #1 ?

**Comment by EvilPort2** [comment]
Yes. It is related.
Read the docs of the VideoCapture method of OpenCV. You will be able to solve the error.

**Comment by EvilPort2** [comment]
The bug has been fixed.

**Comment by EvilPort2** [comment]
sorry for what i said earlier. now this should be fixed
