### ISSUE TITLE
Error about executing recognize_gestures.py 

### ISSUE THREAD

**Issue by BrianVubao** [EvilPort2/Sign-Language#26]
When I try to run recognize_gestures.py or fun_util.py. I get this error. I'm assuming I installed some packages via pip incorrectly. I don't know how to fix this. Could anyone please help me, Thank you.

Using TensorFlow backend.
[ WARN:0] videoio(MSMF): can't grab frame. Error: -2147483638
[ WARN:1] terminating async callback
Traceback (most recent call last):
  File "recognize_gesture.py", line 140, in <module>
    recognize()
  File "recognize_gesture.py", line 110, in recognize
    if len(contours) > 0:
TypeError: object of type 'NoneType' has no len()
[ WARN:0] terminating async callback

**Comment by EvilPort2** [comment]
This is something I don't know. No idea as to why that is happening

**Comment by EvilPort2** [comment]
I have fixed the error. It was OpenCV version problem. I was using the older one. The OpenCV 4.0 compatibility has been added

**Comment by BrianVubao** [comment]
> I have fixed the error. It was OpenCV version problem. I was using the older one. The OpenCV 4.0 compatibility has been added

Alright, thank you. I will attend to my side. It seems to work fine.
