### ISSUE TITLE
Getting EOF Error in loading hist pickle

### ISSUE THREAD

**Issue by mmanishh** [EvilPort2/Sign-Language#7]
I am getting  EOF Error in loading hist pickle in file recognize_gesture.py at line 84

**Comment by EvilPort2** [comment]
This error never occurred to me. Try creating the hist file again using set_hand_hist.py file

**Comment by mmanishh** [comment]
@EvilPort2  What does the set_hand_hist.py file does ?

**Comment by EvilPort2** [comment]
it creates the histogram for histogram backprojection
