### ISSUE TITLE
error about create_gestures.py

### ISSUE THREAD

**Issue by zhaobaozi** [EvilPort2/Sign-Language#8]
hi,
   when i run create_gestures.py,i meet that
cv2.error: /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/imgproc/src/contours.cpp:1904: error: (-215) contour.checkVector(2) >= 0 && (contour.depth() == CV_32F || contour.depth() == CV_32S) in function contourArea
  what is the wrong?

**Comment by EvilPort2** [comment]
need the full error to resolve the problem.
but it seems like your are not using OpenCV 3.4. if that is the case, try installing OpenCV 3.4 and run the program again.

**Comment by zhaobaozi** [comment]
@EvilPort2 hi thanks,just as you said,i have finish this question.but i meet another one,when i do in python3 recognize_gesture.py, the terminal have the number,such as '3  0.7800',but the recognizing gesture allways show '1',what can i do? thanks

**Comment by zhaobaozi** [comment]
HI @EvilPort2 ,i have finished this question by what you said,but i meet another question,
when i run fun_util.py and choose the calculator mode,i just can enter the first number,How can I turn to the second number?i can't activing the operation.

**Comment by zhaobaozi** [comment]
what is the "best of luck" gesture ?i neet to creat?

**Comment by EvilPort2** [comment]
it is the thumbs up sign

**Comment by zhaobaozi** [comment]
@EvilPort2 i delete gestures create by you,and add the gesture myselt,so i can also use the "best of luck"?where i can define it?

**Comment by EvilPort2** [comment]
yes. you can use any gesture you want. but if you would have to change the 'best of luck' sign you would have to change the source code.

**Comment by zhaobaozi** [comment]
haha..so can i use my add gestures(delete your gestures) and the"best of luck"(your define)simultaneously?

**Comment by zhaobaozi** [comment]
and i only see 'best of luck 'in fun_util.py,if i change it,where i should change?the pred_text == 1 in fun_util.py means the greature no. we define in create_greatures.py?

**Comment by zhaobaozi** [comment]
ok i know..thanks very much :)
